/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthDashboardUserImport } from './routes/_auth/dashboard/user'
import { Route as AuthDashboardPmImport } from './routes/_auth/dashboard/pm'
import { Route as AuthDashboardAdminImport } from './routes/_auth/dashboard/admin'
import { Route as AuthDashboardAdminIndexImport } from './routes/_auth/dashboard/admin/index'
import { Route as AuthDashboardAdminUsersImport } from './routes/_auth/dashboard/admin/users'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardUserRoute = AuthDashboardUserImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardPmRoute = AuthDashboardPmImport.update({
  id: '/dashboard/pm',
  path: '/dashboard/pm',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardAdminRoute = AuthDashboardAdminImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardAdminIndexRoute = AuthDashboardAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardAdminRoute,
} as any)

const AuthDashboardAdminUsersRoute = AuthDashboardAdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthDashboardAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard/admin': {
      id: '/_auth/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthDashboardAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/pm': {
      id: '/_auth/dashboard/pm'
      path: '/dashboard/pm'
      fullPath: '/dashboard/pm'
      preLoaderRoute: typeof AuthDashboardPmImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/user': {
      id: '/_auth/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof AuthDashboardUserImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/admin/users': {
      id: '/_auth/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthDashboardAdminUsersImport
      parentRoute: typeof AuthDashboardAdminImport
    }
    '/_auth/dashboard/admin/': {
      id: '/_auth/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthDashboardAdminIndexImport
      parentRoute: typeof AuthDashboardAdminImport
    }
  }
}

// Create and export the route tree

interface AuthDashboardAdminRouteChildren {
  AuthDashboardAdminUsersRoute: typeof AuthDashboardAdminUsersRoute
  AuthDashboardAdminIndexRoute: typeof AuthDashboardAdminIndexRoute
}

const AuthDashboardAdminRouteChildren: AuthDashboardAdminRouteChildren = {
  AuthDashboardAdminUsersRoute: AuthDashboardAdminUsersRoute,
  AuthDashboardAdminIndexRoute: AuthDashboardAdminIndexRoute,
}

const AuthDashboardAdminRouteWithChildren =
  AuthDashboardAdminRoute._addFileChildren(AuthDashboardAdminRouteChildren)

interface AuthRouteChildren {
  AuthDashboardAdminRoute: typeof AuthDashboardAdminRouteWithChildren
  AuthDashboardPmRoute: typeof AuthDashboardPmRoute
  AuthDashboardUserRoute: typeof AuthDashboardUserRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardAdminRoute: AuthDashboardAdminRouteWithChildren,
  AuthDashboardPmRoute: AuthDashboardPmRoute,
  AuthDashboardUserRoute: AuthDashboardUserRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof AuthDashboardAdminRouteWithChildren
  '/dashboard/pm': typeof AuthDashboardPmRoute
  '/dashboard/user': typeof AuthDashboardUserRoute
  '/dashboard/admin/users': typeof AuthDashboardAdminUsersRoute
  '/dashboard/admin/': typeof AuthDashboardAdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/pm': typeof AuthDashboardPmRoute
  '/dashboard/user': typeof AuthDashboardUserRoute
  '/dashboard/admin/users': typeof AuthDashboardAdminUsersRoute
  '/dashboard/admin': typeof AuthDashboardAdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard/admin': typeof AuthDashboardAdminRouteWithChildren
  '/_auth/dashboard/pm': typeof AuthDashboardPmRoute
  '/_auth/dashboard/user': typeof AuthDashboardUserRoute
  '/_auth/dashboard/admin/users': typeof AuthDashboardAdminUsersRoute
  '/_auth/dashboard/admin/': typeof AuthDashboardAdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/pm'
    | '/dashboard/user'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard/pm'
    | '/dashboard/user'
    | '/dashboard/admin/users'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard/admin'
    | '/_auth/dashboard/pm'
    | '/_auth/dashboard/user'
    | '/_auth/dashboard/admin/users'
    | '/_auth/dashboard/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard/admin",
        "/_auth/dashboard/pm",
        "/_auth/dashboard/user"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/dashboard/admin": {
      "filePath": "_auth/dashboard/admin.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/dashboard/admin/users",
        "/_auth/dashboard/admin/"
      ]
    },
    "/_auth/dashboard/pm": {
      "filePath": "_auth/dashboard/pm.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard/user": {
      "filePath": "_auth/dashboard/user.tsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard/admin/users": {
      "filePath": "_auth/dashboard/admin/users.tsx",
      "parent": "/_auth/dashboard/admin"
    },
    "/_auth/dashboard/admin/": {
      "filePath": "_auth/dashboard/admin/index.tsx",
      "parent": "/_auth/dashboard/admin"
    }
  }
}
ROUTE_MANIFEST_END */
