/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthDashboardUserImport } from './routes/_auth/dashboard/user'
import { Route as AuthDashboardPmImport } from './routes/_auth/dashboard/pm'
import { Route as AuthDashboardAdminImport } from './routes/_auth/dashboard/admin'
import { Route as AuthDashboardUserIndexImport } from './routes/_auth/dashboard/user/index'
import { Route as AuthDashboardPmIndexImport } from './routes/_auth/dashboard/pm/index'
import { Route as AuthDashboardAdminIndexImport } from './routes/_auth/dashboard/admin/index'
import { Route as AuthDashboardAdminUsersImport } from './routes/_auth/dashboard/admin/users'
import { Route as AuthDashboardPmProjectsIndexImport } from './routes/_auth/dashboard/pm/projects.index'
import { Route as AuthDashboardAdminProjectsIndexImport } from './routes/_auth/dashboard/admin/projects.index'
import { Route as AuthDashboardUserProjectsIdImport } from './routes/_auth/dashboard/user/projects.$id'
import { Route as AuthDashboardPmProjectsIdImport } from './routes/_auth/dashboard/pm/projects.$id'
import { Route as AuthDashboardAdminProjectsCreateImport } from './routes/_auth/dashboard/admin/projects.create'
import { Route as AuthDashboardAdminProjectsIdImport } from './routes/_auth/dashboard/admin/projects.$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthDashboardUserRoute = AuthDashboardUserImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardPmRoute = AuthDashboardPmImport.update({
  id: '/dashboard/pm',
  path: '/dashboard/pm',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardAdminRoute = AuthDashboardAdminImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardUserIndexRoute = AuthDashboardUserIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardUserRoute,
} as any)

const AuthDashboardPmIndexRoute = AuthDashboardPmIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardPmRoute,
} as any)

const AuthDashboardAdminIndexRoute = AuthDashboardAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardAdminRoute,
} as any)

const AuthDashboardAdminUsersRoute = AuthDashboardAdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthDashboardAdminRoute,
} as any)

const AuthDashboardPmProjectsIndexRoute =
  AuthDashboardPmProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthDashboardPmRoute,
  } as any)

const AuthDashboardAdminProjectsIndexRoute =
  AuthDashboardAdminProjectsIndexImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthDashboardAdminRoute,
  } as any)

const AuthDashboardUserProjectsIdRoute =
  AuthDashboardUserProjectsIdImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthDashboardUserRoute,
  } as any)

const AuthDashboardPmProjectsIdRoute = AuthDashboardPmProjectsIdImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthDashboardPmRoute,
} as any)

const AuthDashboardAdminProjectsCreateRoute =
  AuthDashboardAdminProjectsCreateImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthDashboardAdminRoute,
  } as any)

const AuthDashboardAdminProjectsIdRoute =
  AuthDashboardAdminProjectsIdImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthDashboardAdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard/admin': {
      id: '/_auth/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthDashboardAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/pm': {
      id: '/_auth/dashboard/pm'
      path: '/dashboard/pm'
      fullPath: '/dashboard/pm'
      preLoaderRoute: typeof AuthDashboardPmImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/user': {
      id: '/_auth/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof AuthDashboardUserImport
      parentRoute: typeof AuthImport
    }
    '/_auth/dashboard/admin/users': {
      id: '/_auth/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthDashboardAdminUsersImport
      parentRoute: typeof AuthDashboardAdminImport
    }
    '/_auth/dashboard/admin/': {
      id: '/_auth/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthDashboardAdminIndexImport
      parentRoute: typeof AuthDashboardAdminImport
    }
    '/_auth/dashboard/pm/': {
      id: '/_auth/dashboard/pm/'
      path: '/'
      fullPath: '/dashboard/pm/'
      preLoaderRoute: typeof AuthDashboardPmIndexImport
      parentRoute: typeof AuthDashboardPmImport
    }
    '/_auth/dashboard/user/': {
      id: '/_auth/dashboard/user/'
      path: '/'
      fullPath: '/dashboard/user/'
      preLoaderRoute: typeof AuthDashboardUserIndexImport
      parentRoute: typeof AuthDashboardUserImport
    }
    '/_auth/dashboard/admin/projects/$id': {
      id: '/_auth/dashboard/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/admin/projects/$id'
      preLoaderRoute: typeof AuthDashboardAdminProjectsIdImport
      parentRoute: typeof AuthDashboardAdminImport
    }
    '/_auth/dashboard/admin/projects/create': {
      id: '/_auth/dashboard/admin/projects/create'
      path: '/projects/create'
      fullPath: '/dashboard/admin/projects/create'
      preLoaderRoute: typeof AuthDashboardAdminProjectsCreateImport
      parentRoute: typeof AuthDashboardAdminImport
    }
    '/_auth/dashboard/pm/projects/$id': {
      id: '/_auth/dashboard/pm/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/pm/projects/$id'
      preLoaderRoute: typeof AuthDashboardPmProjectsIdImport
      parentRoute: typeof AuthDashboardPmImport
    }
    '/_auth/dashboard/user/projects/$id': {
      id: '/_auth/dashboard/user/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/user/projects/$id'
      preLoaderRoute: typeof AuthDashboardUserProjectsIdImport
      parentRoute: typeof AuthDashboardUserImport
    }
    '/_auth/dashboard/admin/projects/': {
      id: '/_auth/dashboard/admin/projects/'
      path: '/projects'
      fullPath: '/dashboard/admin/projects'
      preLoaderRoute: typeof AuthDashboardAdminProjectsIndexImport
      parentRoute: typeof AuthDashboardAdminImport
    }
    '/_auth/dashboard/pm/projects/': {
      id: '/_auth/dashboard/pm/projects/'
      path: '/projects'
      fullPath: '/dashboard/pm/projects'
      preLoaderRoute: typeof AuthDashboardPmProjectsIndexImport
      parentRoute: typeof AuthDashboardPmImport
    }
  }
}

// Create and export the route tree

interface AuthDashboardAdminRouteChildren {
  AuthDashboardAdminUsersRoute: typeof AuthDashboardAdminUsersRoute
  AuthDashboardAdminIndexRoute: typeof AuthDashboardAdminIndexRoute
  AuthDashboardAdminProjectsIdRoute: typeof AuthDashboardAdminProjectsIdRoute
  AuthDashboardAdminProjectsCreateRoute: typeof AuthDashboardAdminProjectsCreateRoute
  AuthDashboardAdminProjectsIndexRoute: typeof AuthDashboardAdminProjectsIndexRoute
}

const AuthDashboardAdminRouteChildren: AuthDashboardAdminRouteChildren = {
  AuthDashboardAdminUsersRoute: AuthDashboardAdminUsersRoute,
  AuthDashboardAdminIndexRoute: AuthDashboardAdminIndexRoute,
  AuthDashboardAdminProjectsIdRoute: AuthDashboardAdminProjectsIdRoute,
  AuthDashboardAdminProjectsCreateRoute: AuthDashboardAdminProjectsCreateRoute,
  AuthDashboardAdminProjectsIndexRoute: AuthDashboardAdminProjectsIndexRoute,
}

const AuthDashboardAdminRouteWithChildren =
  AuthDashboardAdminRoute._addFileChildren(AuthDashboardAdminRouteChildren)

interface AuthDashboardPmRouteChildren {
  AuthDashboardPmIndexRoute: typeof AuthDashboardPmIndexRoute
  AuthDashboardPmProjectsIdRoute: typeof AuthDashboardPmProjectsIdRoute
  AuthDashboardPmProjectsIndexRoute: typeof AuthDashboardPmProjectsIndexRoute
}

const AuthDashboardPmRouteChildren: AuthDashboardPmRouteChildren = {
  AuthDashboardPmIndexRoute: AuthDashboardPmIndexRoute,
  AuthDashboardPmProjectsIdRoute: AuthDashboardPmProjectsIdRoute,
  AuthDashboardPmProjectsIndexRoute: AuthDashboardPmProjectsIndexRoute,
}

const AuthDashboardPmRouteWithChildren = AuthDashboardPmRoute._addFileChildren(
  AuthDashboardPmRouteChildren,
)

interface AuthDashboardUserRouteChildren {
  AuthDashboardUserIndexRoute: typeof AuthDashboardUserIndexRoute
  AuthDashboardUserProjectsIdRoute: typeof AuthDashboardUserProjectsIdRoute
}

const AuthDashboardUserRouteChildren: AuthDashboardUserRouteChildren = {
  AuthDashboardUserIndexRoute: AuthDashboardUserIndexRoute,
  AuthDashboardUserProjectsIdRoute: AuthDashboardUserProjectsIdRoute,
}

const AuthDashboardUserRouteWithChildren =
  AuthDashboardUserRoute._addFileChildren(AuthDashboardUserRouteChildren)

interface AuthRouteChildren {
  AuthDashboardAdminRoute: typeof AuthDashboardAdminRouteWithChildren
  AuthDashboardPmRoute: typeof AuthDashboardPmRouteWithChildren
  AuthDashboardUserRoute: typeof AuthDashboardUserRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardAdminRoute: AuthDashboardAdminRouteWithChildren,
  AuthDashboardPmRoute: AuthDashboardPmRouteWithChildren,
  AuthDashboardUserRoute: AuthDashboardUserRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof AuthDashboardAdminRouteWithChildren
  '/dashboard/pm': typeof AuthDashboardPmRouteWithChildren
  '/dashboard/user': typeof AuthDashboardUserRouteWithChildren
  '/dashboard/admin/users': typeof AuthDashboardAdminUsersRoute
  '/dashboard/admin/': typeof AuthDashboardAdminIndexRoute
  '/dashboard/pm/': typeof AuthDashboardPmIndexRoute
  '/dashboard/user/': typeof AuthDashboardUserIndexRoute
  '/dashboard/admin/projects/$id': typeof AuthDashboardAdminProjectsIdRoute
  '/dashboard/admin/projects/create': typeof AuthDashboardAdminProjectsCreateRoute
  '/dashboard/pm/projects/$id': typeof AuthDashboardPmProjectsIdRoute
  '/dashboard/user/projects/$id': typeof AuthDashboardUserProjectsIdRoute
  '/dashboard/admin/projects': typeof AuthDashboardAdminProjectsIndexRoute
  '/dashboard/pm/projects': typeof AuthDashboardPmProjectsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin/users': typeof AuthDashboardAdminUsersRoute
  '/dashboard/admin': typeof AuthDashboardAdminIndexRoute
  '/dashboard/pm': typeof AuthDashboardPmIndexRoute
  '/dashboard/user': typeof AuthDashboardUserIndexRoute
  '/dashboard/admin/projects/$id': typeof AuthDashboardAdminProjectsIdRoute
  '/dashboard/admin/projects/create': typeof AuthDashboardAdminProjectsCreateRoute
  '/dashboard/pm/projects/$id': typeof AuthDashboardPmProjectsIdRoute
  '/dashboard/user/projects/$id': typeof AuthDashboardUserProjectsIdRoute
  '/dashboard/admin/projects': typeof AuthDashboardAdminProjectsIndexRoute
  '/dashboard/pm/projects': typeof AuthDashboardPmProjectsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/dashboard/admin': typeof AuthDashboardAdminRouteWithChildren
  '/_auth/dashboard/pm': typeof AuthDashboardPmRouteWithChildren
  '/_auth/dashboard/user': typeof AuthDashboardUserRouteWithChildren
  '/_auth/dashboard/admin/users': typeof AuthDashboardAdminUsersRoute
  '/_auth/dashboard/admin/': typeof AuthDashboardAdminIndexRoute
  '/_auth/dashboard/pm/': typeof AuthDashboardPmIndexRoute
  '/_auth/dashboard/user/': typeof AuthDashboardUserIndexRoute
  '/_auth/dashboard/admin/projects/$id': typeof AuthDashboardAdminProjectsIdRoute
  '/_auth/dashboard/admin/projects/create': typeof AuthDashboardAdminProjectsCreateRoute
  '/_auth/dashboard/pm/projects/$id': typeof AuthDashboardPmProjectsIdRoute
  '/_auth/dashboard/user/projects/$id': typeof AuthDashboardUserProjectsIdRoute
  '/_auth/dashboard/admin/projects/': typeof AuthDashboardAdminProjectsIndexRoute
  '/_auth/dashboard/pm/projects/': typeof AuthDashboardPmProjectsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/pm'
    | '/dashboard/user'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
    | '/dashboard/pm/'
    | '/dashboard/user/'
    | '/dashboard/admin/projects/$id'
    | '/dashboard/admin/projects/create'
    | '/dashboard/pm/projects/$id'
    | '/dashboard/user/projects/$id'
    | '/dashboard/admin/projects'
    | '/dashboard/pm/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard/admin/users'
    | '/dashboard/admin'
    | '/dashboard/pm'
    | '/dashboard/user'
    | '/dashboard/admin/projects/$id'
    | '/dashboard/admin/projects/create'
    | '/dashboard/pm/projects/$id'
    | '/dashboard/user/projects/$id'
    | '/dashboard/admin/projects'
    | '/dashboard/pm/projects'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/dashboard/admin'
    | '/_auth/dashboard/pm'
    | '/_auth/dashboard/user'
    | '/_auth/dashboard/admin/users'
    | '/_auth/dashboard/admin/'
    | '/_auth/dashboard/pm/'
    | '/_auth/dashboard/user/'
    | '/_auth/dashboard/admin/projects/$id'
    | '/_auth/dashboard/admin/projects/create'
    | '/_auth/dashboard/pm/projects/$id'
    | '/_auth/dashboard/user/projects/$id'
    | '/_auth/dashboard/admin/projects/'
    | '/_auth/dashboard/pm/projects/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard/admin",
        "/_auth/dashboard/pm",
        "/_auth/dashboard/user"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/dashboard/admin": {
      "filePath": "_auth/dashboard/admin.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/dashboard/admin/users",
        "/_auth/dashboard/admin/",
        "/_auth/dashboard/admin/projects/$id",
        "/_auth/dashboard/admin/projects/create",
        "/_auth/dashboard/admin/projects/"
      ]
    },
    "/_auth/dashboard/pm": {
      "filePath": "_auth/dashboard/pm.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/dashboard/pm/",
        "/_auth/dashboard/pm/projects/$id",
        "/_auth/dashboard/pm/projects/"
      ]
    },
    "/_auth/dashboard/user": {
      "filePath": "_auth/dashboard/user.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/dashboard/user/",
        "/_auth/dashboard/user/projects/$id"
      ]
    },
    "/_auth/dashboard/admin/users": {
      "filePath": "_auth/dashboard/admin/users.tsx",
      "parent": "/_auth/dashboard/admin"
    },
    "/_auth/dashboard/admin/": {
      "filePath": "_auth/dashboard/admin/index.tsx",
      "parent": "/_auth/dashboard/admin"
    },
    "/_auth/dashboard/pm/": {
      "filePath": "_auth/dashboard/pm/index.tsx",
      "parent": "/_auth/dashboard/pm"
    },
    "/_auth/dashboard/user/": {
      "filePath": "_auth/dashboard/user/index.tsx",
      "parent": "/_auth/dashboard/user"
    },
    "/_auth/dashboard/admin/projects/$id": {
      "filePath": "_auth/dashboard/admin/projects.$id.tsx",
      "parent": "/_auth/dashboard/admin"
    },
    "/_auth/dashboard/admin/projects/create": {
      "filePath": "_auth/dashboard/admin/projects.create.tsx",
      "parent": "/_auth/dashboard/admin"
    },
    "/_auth/dashboard/pm/projects/$id": {
      "filePath": "_auth/dashboard/pm/projects.$id.tsx",
      "parent": "/_auth/dashboard/pm"
    },
    "/_auth/dashboard/user/projects/$id": {
      "filePath": "_auth/dashboard/user/projects.$id.tsx",
      "parent": "/_auth/dashboard/user"
    },
    "/_auth/dashboard/admin/projects/": {
      "filePath": "_auth/dashboard/admin/projects.index.tsx",
      "parent": "/_auth/dashboard/admin"
    },
    "/_auth/dashboard/pm/projects/": {
      "filePath": "_auth/dashboard/pm/projects.index.tsx",
      "parent": "/_auth/dashboard/pm"
    }
  }
}
ROUTE_MANIFEST_END */
